version: "3.9"

services:
  api:
    build: ./Server
    environment:
      DB_SERVER: "${DB_SERVER}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5000:80"
